<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AsmResolver">
      <HintPath>D:\Schedule I\Builds\Public\MelonLoader\net6\AsmResolver.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.DotNet">
      <HintPath>D:\Schedule I\Builds\Public\MelonLoader\net6\AsmResolver.DotNet.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.PE">
      <HintPath>D:\Schedule I\Builds\Public\MelonLoader\net6\AsmResolver.PE.dll</HintPath>
    </Reference>
    <Reference Include="AsmResolver.PE.File">
      <HintPath>D:\Schedule I\Builds\Public\MelonLoader\net6\AsmResolver.PE.File.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
